apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" . }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - "/jet-supervision"
