{{- if .Values.supervisionTLSSecret | empty | not }}
{{- with .Values.supervisionTLSSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" $ }}-tls-secret
  labels:
    {{ include "jet-supervision-helm-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Please provide `certificate` for supervisionTLSSecret" .certificate }}
  tls.key: {{ required "Please provide `key` for supervisionTLSSecret" .key }}
{{- end }}
{{- end }}
