{{- if .Values.appTLSSecret | empty | not }}
{{- with .Values.appTLSSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jet-app-helm-chart.fullname" $ }}-tls-secret
  labels:
    {{ include "jet-app-helm-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Please provide `certificate` for appTLSSecret" .certificate }}
  tls.key: {{ required "Please provide `key` for appTLSSecret" .key }}
{{- end }}
{{- end }}
