{{- if .Values.supervisionTLSSecret | empty | not }}
{{- with .Values.supervisionTLSSecret }}
{{- if .certificate | empty }}
{{- fail "Please provide `certificate` for supervisionTLSSecret" }}
{{- end }}
{{- if .key | empty }}
{{- fail "Please provide `key` for supervisionTLSSecret" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" $ }}-tls-secret
  labels:
    {{ include "jet-supervision-helm-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}
