apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" . }}-action-list
  labels:
    {{- include "jet-supervision-helm-chart.labels" . | nindent 4 }}
data:
  action-list.env: |-
    {{- range $line := .Files.Lines "action-list.env" }}
    {{- if not (hasPrefix "#" $line) }}
    {{ $line }}
    {{- end }}
    {{- end }}

