apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" . }}-action-list
  labels:
    {{- include "jet-supervision-helm-chart.labels" . | nindent 4 }}
data:
  {{- $binary := required "Please set `actionList` in `values.local.yaml`" .Values.actionList }}

  {{- range $line := mustRegexSplit "\n" $binary -1  }}
  {{- $line = nospace $line }}
  {{- if and (not (hasPrefix "#" $line)) ($line | empty | not) }}

  {{- $kv := mustRegexSplit "=" $line 2 }}
  {{ $kv | first }}: {{ $kv | last }}
  {{- end }}

  {{- end }}
