apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" . }}-action-list
  labels:
    {{- include "jet-supervision-helm-chart.labels" . | nindent 4 }}
data:
  {{- range $line := .Files.Lines "action-list.env" }}
  {{- if not (hasPrefix "#" $line) }}

  {{- $kv := splitList "=" $line -}}
  {{- $k := first $kv -}}
  {{- if $k }}
    {{ $k }}: {{ last $kv | quote }}
  {{- end }}

  {{- end }}
  {{- end }}
