apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-supervision-helm-chart.fullname" . }}
  labels:
    {{- include "jet-supervision-helm-chart.labels" . | nindent 4 }}
data:
  APPLICATION_NAME: {{ .Values.applicationName }}
  BASE_URL: {{ .Values.baseUrl }}
  SENTRY_DSN: {{ .Values.sentryDsn | quote }}
  SENTRY_RELEASE: {{ .Values.sentryRelease | quote }}
  HOST: {{ .Values.jetHost }}
  SSL: {{ .Values.jetSSL | quote }}
