apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-app-supervision-gxzh.fullname" . }}
  labels:
    {{- include "jet-app-supervision-gxzh.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.baseUrl }}
  SENTRY_DSN: {{ .Values.sentryDsn | quote }}
  HOST: {{ .Values.jetHost }}
  SSL: {{ .Values.jetSSL | quote }}
