apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-app-helm-chart.fullname" . }}
  labels:
    {{- include "jet-app-helm-chart.labels" . | nindent 4 }}
data:
  .env: |
    APPLICATION_NAME={{ .Values.applicationName }}
    BASE_URL={{ include "jet-app-helm-chart.app-path" . }}
    JET_ENDPOINT={{ .Values.jetEndpoint }}

    {{- $binary := required "Please set `actionList` in `values.local.yaml`" .Values.actionList }}

    {{- range $line := mustRegexSplit "\n" $binary -1  }}
    {{- $line = nospace $line }}
    {{- if and (not (hasPrefix "#" $line)) ($line | empty | not) }}

    {{- $kv := mustRegexSplit "=" $line 2 }}
    {{ $kv | first }}={{ $kv | last }}
    {{- end }}

    {{- end }}
