apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-app-helm-chart.fullname" . }}
  labels:
    {{- include "jet-app-helm-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80 
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "jet-app-helm-chart.selectorLabels" . | nindent 4 }}
    app: {{ template "jet-app-helm-chart.fullname" . }}
